SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE `ai_action_audit` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `investigation_id` bigint NOT NULL,
  `action_plan_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `event_type` varchar(255) NOT NULL,
  `actor` varchar(255) DEFAULT NULL,
  `decision` varchar(255) DEFAULT NULL,
  `risk_level` varchar(255) DEFAULT NULL,
  `detail_json` longtext,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_ai_action_audit_investigation_created` (`investigation_id`,`created_at`),
  KEY `idx_ai_action_audit_action_created` (`action_plan_id`,`created_at`),
  KEY `idx_ai_action_audit_user_created` (`user_id`,`created_at`),
  KEY `idx_ai_action_audit_event_created` (`event_type`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `ai_action_plan` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `action_type` varchar(50) NOT NULL,
  `command_text` text,
  `created_at` datetime(6) DEFAULT NULL,
  `hypothesis_id` bigint DEFAULT NULL,
  `investigation_id` bigint NOT NULL,
  `requires_approval` bit(1) DEFAULT NULL,
  `risk_level` varchar(20) DEFAULT NULL,
  `rollback_plan` text,
  `runbook_ref` varchar(500) DEFAULT NULL,
  `status` varchar(20) DEFAULT NULL,
  `approved_by` varchar(100) DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `approval_note` text,
  `retry_count` int NOT NULL DEFAULT '0',
  `title` varchar(255) NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_action_plan_approved_at` (`approved_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `ai_action_run` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `action_plan_id` bigint NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `ended_at` datetime(6) DEFAULT NULL,
  `error_message` text,
  `execution_mode` varchar(20) DEFAULT NULL,
  `executor` varchar(100) DEFAULT NULL,
  `investigation_id` bigint NOT NULL,
  `output_text` mediumtext,
  `started_at` datetime(6) DEFAULT NULL,
  `status` varchar(20) DEFAULT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `ai_hypothesis` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `confidence` double DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `investigation_id` bigint NOT NULL,
  `rank_order` int DEFAULT NULL,
  `reasoning` text,
  `status` varchar(20) DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `ai_investigation` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `closed_at` datetime(6) DEFAULT NULL,
  `confidence` double DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `incident_id` bigint DEFAULT NULL,
  `root_cause` varchar(300) DEFAULT NULL,
  `severity` varchar(10) DEFAULT NULL,
  `started_at` datetime(6) DEFAULT NULL,
  `status` varchar(30) DEFAULT NULL,
  `summary` text,
  `target_id` bigint DEFAULT NULL,
  `title` varchar(200) DEFAULT NULL,
  `trigger_source` varchar(30) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `ai_model_trace` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `investigation_id` bigint DEFAULT NULL,
  `phase` varchar(255) DEFAULT NULL,
  `model_name` varchar(255) DEFAULT NULL,
  `prompt_text` longtext,
  `response_text` longtext,
  `prompt_tokens` int DEFAULT NULL,
  `response_tokens` int DEFAULT NULL,
  `latency_ms` bigint DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `error_message` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_model_trace_user_time` (`user_id`,`created_at`),
  KEY `idx_model_trace_investigation_time` (`investigation_id`,`created_at`),
  KEY `idx_model_trace_phase_time` (`phase`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `ai_observation` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `confidence` double DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `hostname` varchar(255) DEFAULT NULL,
  `investigation_id` bigint NOT NULL,
  `metric_name` varchar(50) DEFAULT NULL,
  `metric_value` double DEFAULT NULL,
  `observed_at` datetime(6) DEFAULT NULL,
  `payload_json` longtext,
  `source_ref` varchar(255) DEFAULT NULL,
  `type` varchar(30) NOT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `ai_report_snapshot` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `format` varchar(20) NOT NULL,
  `investigation_id` bigint NOT NULL,
  `report_json` longtext,
  `report_markdown` mediumtext,
  `user_id` bigint NOT NULL,
  `version_no` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `ai_rollback_run` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `action_plan_id` bigint NOT NULL,
  `investigation_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `executor` varchar(255) DEFAULT NULL,
  `drill_mode` tinyint(1) NOT NULL DEFAULT '0',
  `execution_mode` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `note_text` text,
  `output_text` mediumtext,
  `error_message` text,
  `started_at` datetime DEFAULT NULL,
  `ended_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_ai_rollback_run_action_created` (`action_plan_id`,`created_at`),
  KEY `idx_ai_rollback_run_investigation_created` (`investigation_id`,`created_at`),
  KEY `idx_ai_rollback_run_user_created` (`user_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `alert_escalation_policy` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `p1_intervals` varchar(100) NOT NULL,
  `p2_intervals` varchar(100) NOT NULL,
  `p3_intervals` varchar(100) NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_alert_escalation_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `alert_threshold_config` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `consecutive_breach_count` int NOT NULL,
  `cpu_threshold` double NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `disk_threshold` double NOT NULL,
  `memory_threshold` double NOT NULL,
  `process_count_threshold` int NOT NULL,
  `silence_seconds` int NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_alert_threshold_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `anomaly_result` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `target_id` bigint DEFAULT NULL,
  `hostname` varchar(255) DEFAULT NULL,
  `metric_key` varchar(255) NOT NULL,
  `score` double NOT NULL,
  `baseline` double DEFAULT NULL,
  `observed` double DEFAULT NULL,
  `severity` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `detected_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `source_metric_id` bigint DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_anomaly_user_detected` (`user_id`,`detected_at`),
  KEY `idx_anomaly_target_metric_time` (`target_id`,`metric_key`,`detected_at`),
  KEY `idx_anomaly_status_time` (`status`,`detected_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `audit_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint DEFAULT NULL,
  `actor` varchar(100) DEFAULT NULL,
  `action` varchar(80) NOT NULL,
  `resource_type` varchar(80) DEFAULT NULL,
  `resource_id` bigint DEFAULT NULL,
  `ip_address` varchar(64) DEFAULT NULL,
  `detail_json` longtext,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_audit_user_time` (`user_id`,`created_at`),
  KEY `idx_audit_action_time` (`action`,`created_at`),
  KEY `idx_audit_resource` (`resource_type`,`resource_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `incident_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `hostname` varchar(255) DEFAULT NULL,
  `message` varchar(255) DEFAULT NULL,
  `metric_name` varchar(255) DEFAULT NULL,
  `metric_value` double DEFAULT NULL,
  `threshold` double DEFAULT NULL,
  `target_id` bigint DEFAULT NULL,
  `user_id` bigint DEFAULT NULL,
  `acknowledged_at` datetime(6) DEFAULT NULL,
  `resolved_at` datetime(6) DEFAULT NULL,
  `status` varchar(20) DEFAULT NULL,
  `escalation_level` int DEFAULT NULL,
  `last_notified_at` datetime(6) DEFAULT NULL,
  `next_notify_at` datetime(6) DEFAULT NULL,
  `severity` varchar(10) DEFAULT NULL,
  `fingerprint` varchar(255) DEFAULT NULL,
  `occurrence_count` int NOT NULL DEFAULT '1',
  `suppressed_count` int NOT NULL DEFAULT '0',
  `first_seen_at` datetime DEFAULT NULL,
  `last_seen_at` datetime DEFAULT NULL,
  `source_type` varchar(30) NOT NULL DEFAULT 'METRIC',
  `source_ref` varchar(255) DEFAULT NULL,
  `service_name` varchar(255) DEFAULT NULL,
  `trace_id` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_incident_user_fingerprint_status` (`user_id`,`fingerprint`,`status`),
  KEY `idx_incident_target_metric_status` (`target_id`,`metric_name`,`status`),
  KEY `idx_incident_last_seen_at` (`last_seen_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `log_record` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `target_id` bigint DEFAULT NULL,
  `hostname` varchar(255) DEFAULT NULL,
  `service_name` varchar(255) DEFAULT NULL,
  `source` varchar(255) DEFAULT NULL,
  `level` varchar(255) DEFAULT NULL,
  `message` text,
  `trace_id` varchar(255) DEFAULT NULL,
  `labels_json` longtext,
  `occurred_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_log_record_user_time` (`user_id`,`occurred_at`),
  KEY `idx_log_record_target_time` (`target_id`,`occurred_at`),
  KEY `idx_log_record_trace_id` (`trace_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `monitor_targets` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `agent_key` varchar(64) NOT NULL,
  `agent_version` varchar(64) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `enabled` bit(1) NOT NULL,
  `hostname` varchar(255) DEFAULT NULL,
  `ip_address` varchar(64) DEFAULT NULL,
  `last_heartbeat_at` datetime(6) DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `status` varchar(20) DEFAULT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKjfnqkgvqfm495oo48jl90tfrh` (`agent_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `notification_channel` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `enabled` bit(1) NOT NULL,
  `last_error` varchar(500) DEFAULT NULL,
  `last_notified_at` datetime(6) DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `secret` varchar(255) DEFAULT NULL,
  `type` varchar(20) NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `user_id` bigint NOT NULL,
  `webhook_url` varchar(500) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `notification_delivery_log` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `channel_id` bigint DEFAULT NULL,
  `channel_name` varchar(100) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `error_message` varchar(500) DEFAULT NULL,
  `http_status` int DEFAULT NULL,
  `incident_id` bigint NOT NULL,
  `response_body` varchar(1000) DEFAULT NULL,
  `status` varchar(20) NOT NULL,
  `target` varchar(500) NOT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `rca_report` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `investigation_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  `incident_id` bigint DEFAULT NULL,
  `target_id` bigint DEFAULT NULL,
  `summary_md` mediumtext,
  `evidence_json` longtext,
  `confidence` double DEFAULT NULL,
  `model_name` varchar(255) DEFAULT NULL,
  `prompt_hash` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_rca_investigation_created` (`investigation_id`,`created_at`),
  KEY `idx_rca_user_created` (`user_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `system_metrics_history` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `cpu_usage` double DEFAULT NULL,
  `hostname` varchar(255) DEFAULT NULL,
  `mem_usage` double DEFAULT NULL,
  `timestamp` datetime(6) DEFAULT NULL,
  `target_id` bigint DEFAULT NULL,
  `user_id` bigint DEFAULT NULL,
  `disk_usage` double DEFAULT NULL,
  `net_rx_bytes_per_sec` double DEFAULT NULL,
  `net_tx_bytes_per_sec` double DEFAULT NULL,
  `process_count` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `target_threshold_config` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `target_id` bigint NOT NULL,
  `cpu_threshold` double DEFAULT NULL,
  `memory_threshold` double DEFAULT NULL,
  `disk_threshold` double DEFAULT NULL,
  `process_count_threshold` int DEFAULT NULL,
  `consecutive_breach_count` int DEFAULT NULL,
  `silence_seconds` int DEFAULT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_target_threshold_target` (`target_id`),
  KEY `idx_target_threshold_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `trace_span` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `target_id` bigint DEFAULT NULL,
  `hostname` varchar(255) DEFAULT NULL,
  `service_name` varchar(255) DEFAULT NULL,
  `trace_id` varchar(255) NOT NULL,
  `span_id` varchar(255) DEFAULT NULL,
  `parent_span_id` varchar(255) DEFAULT NULL,
  `operation_name` varchar(255) DEFAULT NULL,
  `duration_ms` bigint DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `attributes_json` longtext,
  `started_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_trace_span_user_time` (`user_id`,`started_at`),
  KEY `idx_trace_span_target_time` (`target_id`,`started_at`),
  KEY `idx_trace_span_trace_id` (`trace_id`),
  KEY `idx_trace_span_service_time` (`service_name`,`started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `users` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `email` varchar(100) NOT NULL,
  `enabled` bit(1) NOT NULL,
  `password` varchar(255) NOT NULL,
  `role` enum('ADMIN','OPS','AUDITOR','USER') NOT NULL,
  `username` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK6dotkott2kjsp8vw4d0m25fb7` (`email`),
  UNIQUE KEY `UKr43af9ap4edm43mmtq01oddj6` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
SET FOREIGN_KEY_CHECKS=1;
