# 分布式集群模式特有配置
monitor:
  mode: distributed

spring:
  datasource:
    # 注意：这里的 IP 应该是你集群公用的 MySQL 地址
    url: jdbc:mysql://localhost:3307/aiops_monitor?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    redis:
      host: localhost # 集群公用 Redis，用于分布式锁
      port: 6379